#+INCLUDE: "./css/level-0.orgcss" 
#+TITLE:  


* Introduction
  My research is close related to Machine Learning, Optimization, and Humanoid Robot System Design and its Motion Control.  
  During the past four plus years, I collected some useful information to my research and hopefully also to yours.   

* Laboratories and organizations   
 - GRASP in Univ. of Pennsylvania \\
   http://www.grasp.upenn.edu/ \\
   General Robotics, Automation, Sensing and Perception 
 - Auton Lab @ CMU  \\
   http://www.autonlab.org/autonweb/2.html
 - LAIRLab \\
   http://robotwhisperer.org/   \\
 - Stefan Schaal Lab \\
   http://www-clmc.usc.edu/Research/LeggedLocomotion 
 - Sarcos Inc. \\
   http://www.sarcos.com/
 - Boston Dynamics Inc. \\
   http://www.bostondynamics.com/
 - the Institute for Human and Machine Cognition & Yobotics \\
   http://www.ihmc.us/Research/projects/HumanoidRobots/index.html  \\
   Jerry Patt
 - Leg lab in MIT \\
   http://www.ai.mit.edu/projects/leglab/ \\
   Found by Marc Raibert

* Homepage links  
 - http://groups.csail.mit.edu/locomotion/index.html
 - http://www.cs.cmu.edu/~cga/kdc-07/
 - http://people.cs.ubc.ca/~van/papers/index.html    \\
   http://people.cs.ubc.ca/~van/  physically-based animation and simulation
 - http://groups.csail.mit.edu/locomotion/index.html  \\
   MIT Robot Locomotion Group
 - http://alice.nc.huji.ac.il/~tassa/pmwiki.php?n=Main.YuvalTassa   \\
   Yuval Tassa's homepage, who provide DDP code to download. \\
   See also his advisor's homepage \\  
   http://www.cs.washington.edu/homes/todorov/index.htm

* Researchers
 -  Michael Mistry 
    
 -  Dmitry Berenson 
    http://users.wpi.edu/~dberenson/
    
 -  *Luis Sentis*
    Assistant Professor

    Depart. of Mechanical Engineering
    The University of Texas at Austin
    http://www.me.utexas.edu/~lsentis/

 - Christopher G. Atkeson \\
   Machine Learning, Motion Control, Humanoid Robots \\
   http://www.cs.cmu.edu/~cga/
   
 - Andreas Hofmann  \\
   Humanoid Robot Balance & Walk control \\
   http://people.csail.mit.edu/hofma/Index.htm
 - Paul Vernaza \\
   University of Pennsylvania \\
   Machine Learning, Robotics \\
   http://www.seas.upenn.edu/~vernaza/
 - Marc Raibert \\
   Founder of MIT leg lab
   
 - Stefan Schall \\
   Machine Learning, Motion Control, Humanoid Robots  \\
   http://www-clmc.usc.edu/~sschaal/

 - Remi Munos \\
   http://sequel.futurs.inria.fr/munos \\
   Approximate Dynamic Programming, RL, policy gradient, planning
   Variance reduction techniques
 - Jerry Pratt \\
   http://www.ihmc.us/users/jpratt/  \\
   His approach of maximizing speed, agility, and biological similarity
   through the understanding of biological counterparts, is helping to
   remove the stereotype of robots as being clunky, jerky-moving
   machines.
 - Hartmut Geyer \\
   http://www.cs.cmu.edu/~hgeyer/index.html
 - David M. Thompson,    \\
   Class Introduction to the study of human walking  \\
   http://moon.ouhsc.edu/dthompso/
 - Garth Zeglin \\
   #+   one of Chris Lab's members
   http://www.cs.cmu.edu/~garthz/
 - Darrin Bentivegna   \\
   Learning from demonstration & hydraulic control \\ 
   http://www.andrew.cmu.edu/user/darrinb/ 

 - David Mayne \\
   Differential Dynamic Programming  \\
   http://www.ee.ic.ac.uk/CAP/Staff/Dqm/
 - Evangelos Theodorou \\
   PhD student in USC PI^2 \\
   http://www-clmc.usc.edu/Main/EvangelosTheodorou
 - Yuval Tassa \\
   PhD student, DDP, swimmer with code \\
   http://alice.nc.huji.ac.il/~tassa/ 
 - Bill Smart \\
   Washington Univ. \\
   Motion control, reinforce learning \\
   http://www.cse.wustl.edu/~wds/
 - Tom Erez  \\
   PhD student of Bill Smart \\
   #+ , collaborating with Yuval Tassa, \\
   walking control, swimmer, optimal control, reinforcement learning, and adaptive dynamic programming \\
   http://www.cse.wustl.edu/~etom/Main/HomePage

 - Matthew West \\
   Variational Integrator & trajectory optimization \\
   http://lagrange.mechse.illinois.edu/mwest/
 - J.E. Marsden \\
   Variational Integrator & trajectory optimization \\
   http://www.cds.caltech.edu/~marsden/dcm/home
 - Professor Emanuel Todorov \\
   Homepage Website
   http://www.cs.washington.edu/homes/todorov/index.htm
 - Russ Tedrake  \\
   http://groups.csail.mit.edu/locomotion/russt.html
 - Jessy W. Grizzle \\
   Nonlinear Control \\ 
   http://www.eecs.umich.edu/~grizzle/papers/index.html
 - Martin Stolle \\
   PhD thesis on 'Policies based on Libraries' \\
   http://www.cs.cmu.edu/~mstoll/main.shtml
 - Yuval Tassa \\
   PhD student, who use DDP and a trajectory library to control a simulated multi-link swimmer. \\
   http://alice.nc.huji.ac.il/~tassa/pmwiki.php?n=Main.YuvalTassa
 - Matt Zucker \\
   Little dog motion planning \\
   http://www.cs.cmu.edu/~mzucker/
 - Steven H. Collins.  \\
   Efficient bipedal robots based on passive-dynamic walkers \\
   http://www-personal.umich.edu/~shc/
 - Garth Zeglin with CMU\\
   dynamic programming, biped \\
   http://www-old.ri.cmu.edu/people/zeglin_garth.html
 - Jun Morimoto  \\
   Minimax DDP, biped \\
   http://www-old.ri.cmu.edu/people/morimoto_jun.html 
* Optimization Tools
 - KNITRO
   http://www.artelys.com/en/optimization-tools/knitro

 - MOSEK linear programming, mixed integer programming and many types of nonlinear convex optimization problems. 
   http://mosek.com/
 - CPLEX
   http://www-01.ibm.com/software/integration/optimization/cplex-cp-optimizer/
 - GPOPS Open Source Gauss Pseudo-spectral Optimal Control Software 
   http://www.gpops.org/page5/page5.html
 - ACADO Toolkit Open Source Toolkit for Automatic Control and Dynamic
   Optimization (C++, MATLAB interface available)
   http://www.acadotoolkit.org/
 - GSL GNU Scientific Library 
   http://www.gnu.org/software/gsl/manual/html_node/
 - OOL Open Optimization Library 
   http://ool.sourceforge.net/
 - PROPT  Matlab Optimal Control Software (DAE, ODE) (Commercial Software)
   http://tomdyn.com/
 - numerical recipes 
   http://www.fizyka.umk.pl/nrbook/bookcpdf.html
 - NEOS Server for Optimization
   http://www.neos-server.org/neos/
   
* Resource Links
** Motion planning 
   - Motion Strategy Library \\
     http://msl.cs.uiuc.edu/msl/
     The Motion Strategy Library (MSL) allows easy development and testing of motion planning algorithms for a wide variety of applications. The software architecture is object-oriented and the general design is highly modular. It was developed on a Linux system using GNU C++, STL, and the FOX GUI Toolkit.
   - good introduction with animation and photos for RRT
     http://msl.cs.uiuc.edu/rrt/
     wiki
     http://en.wikipedia.org/wiki/Rapidly-exploring_random_tree

** Others    
 - Data Mining by Andrew Moore @CMU \\
   http://www.autonlab.org/tutorials/
 - Virtual humans, a real-time, physical simulation of a human that
   could interact with its virtual environment. \\
   http://www.washedashore.com/Humans/
   
 - CGA dynamic optimization \\
   http://www.cs.cmu.edu/~cga/dynopt/
 - Robert F. Stengel homepage  \\
   optimal control docs
   http://www.princeton.edu/~stengel/
   
 - Dynamic Programming and Optimal Control (Book)
   http://www.athenasc.com/dpbook.html

 - Yobotics! Simulation Construction Set. in Java \\
    http://yobotics.com/simulation/simulation.htm
    
 - C & C++ programming resource
   - boost C++ library
     https://www.boostpro.com/
 - ADIC 
   http://www.mcs.anl.gov/research/projects/adic/
 - Introduction to the study of human walking  \\
   http://moon.ouhsc.edu/dthompso/gait/intro.htm#term
 - CDD  LP solver \\
   http://control.ee.ethz.ch/~hybrid/cdd.php 
 - MPT Multi-Parametric Toolbox \\
   http://control.ee.ethz.ch/~mpt/downloads/ (free)
 - Geometric Bounding Toolbox (GBT 7.3) for MATLAB \\
   http://sysbrain.com/gbt/gbt/index.htm  
 - qpOASES  
   Active Set Strategy  QP online \\
   http://www.kuleuven.be/optec/software/qpOASES 
 - Professor Emanuel Todorov\\
   papers and codes, such as Iterative LQG, Kalman_LQG, Mimimum Jerk trajectory \\
   http://www.cs.washington.edu/homes/todorov/index.htm
 - Optimal Control Systems Class examples and downloadable Matlab code \\
   Department of Electrical and Computer Engineering in Cleveland State University \\
   http://academic.csuohio.edu/simond/courses/eec644/
 - Optimal Control and Estimation Class in Princeton University, good introductions \\
   http://www.princeton.edu/~stengel/MAE546.html
 - Optimal control at Scholarpedia \\
   http://www.scholarpedia.org/article/Optimal_control 
 - Stanford Convex Optimization Coarse, book, videos, and slides\\
   http://www.stanford.edu/~boyd/cvxbook/ 
 - Lectures notes in Dynamic Optimization by Richard Woodward with Texas A&M University \\
   http://agecon2.tamu.edu/people/faculty/woodward-richard/637/notes/default.htm 
 - Control tutorials for Matlab , wonderful resource of learning automatic control \\
   http://www.engin.umich.edu/group/ctm/index.html  
 - Constrained Control and Estimation, an optimization approach  by Graham C. Goodwin \\
   http://www.eng.newcastle.edu.au/eecs/cdsc/books/cce/  
   code, lecture notes, good!!  
 - Reinforcement Learning: An Introduction  by Richard S. Sutton  \\
   free book, code, solutions 
   http://webdocs.cs.ualberta.ca/~sutton/book/the-book.html

* Journals
 - Impact factor search  
   [[http://www.ncba.cn/Sci_Impact_Factor/SciIF.asp][Link here]]
   
 - Transactions on Robotics 
   [[http://www.ieee-ras.org/][Link here]]
   impact factor: 3.02
   issues per year: 6 
   

 - Autonomous Robots 
   [[http://www.springer.com/new+&+forthcoming+titles+/journal/10514][Link here]]
   impact factor: 2.07 


 - International Journal of Robotics Research 
   [[http://www.sagepub.com/journalsProdDesc.nav?prodId=Journal201324][Link here]]
   impact factor: 1.66

 - Robotics and Autonomous Systems 
   [[http://www.elsevier.com/wps/find/journaldescription.cws_home/505622/description#description][Link here]]
   impact factor: 1.33  (5 years)
   frequency: 12

 - Robotics and Computer-Integrated Manufacturing 
   [[http://www.elsevier.com/wps/find/journaldescription.cws_home/704/description#description][Link here]]
   impact factor: 1.09

 - the IEEE Robotics and Automation Magazine
   [[http://www.ieee-ras.org/ram][Link here]]
   impact factor: 0.85
   four issues per year

 - Robotica
   [[http://journals.cambridge.org/action/displayJournal?jid=ROB][Link here]]
   impact factor: 0.781 

 - Journal of Robotic System (Journal of Field Robotics)
   [[http://www3.interscience.wiley.com/journal/117946193/tocgroup][Link here]]
   impact factor: 0.7

 - IEEE Transactions on Automation Science and Engineering
   frequency: 4

 - Advanced Robotics 
   [[http://www.rsj.or.jp/AR/index_e.html][Link here]]
   impact factor: 0.737

 - JOURNAL OF GUIDANCE, CONTROL, AND DYNAMICS
   [[http://www.aiaa.org/content.cfm?pageid=322&lupubid=23][Link here]]
   impact factor: 0.88 (year 2002)
   frequency: 

 - Optimal Control Application and Methods 
   [[http://www3.interscience.wiley.com/journal/2133/home][Link here]]
   impact factor: 0.833 
   Frequency: Approximately 5 times a year 
   review time: 

 - journal of computer science and technology (China)
   [[http://jcst.ict.ac.cn:8080/jcst/EN/column/column4.shtml][Link here]]
   impact fact:  0.576
   issues per year: 6
   
 - IEEE TRANSACTIONS ON AUTOMATIC CONTROL 
   [[http://www.nd.edu/~ieeetac/special.html][Link here]]
   impact factor: 0.8
   issues: 12

 - International Journal of Humanoid Robotics (IJHR)
   [[http://www.worldscinet.com/ijhr/][Link here]]
   impact factor: 0.542 
  
 - Dynamical System An International Journal
   [[http://www.tandf.co.uk/journals/tf/14689367.html][Link here]]
   IPF: 0.718

* Conference
 - IEEE International Symposium on Approximate Dynamic Programming and Reinforcement Learning (ADPRL),
 - ICRA
 - International Conference on Intelligent Robots and Systems (IROS)
 - CLAWAR
 - Humanoids
 - International Conference on Decision and Control (CDC)
 - Robotics Science and Systems (RSS)
 - Advances in Neural Information Processing Systems (NIPS)

#+ - The World Congress on Intelligent Control and Automation  (WCICA)
#+ - Chinese Control and Decision Conference (CCDC)
# * Interesting people & projects 
#  - Siddhartha Srinivasa \\
#    Adjunct professor in CMU, senior scientist of Intel Lab. \\
#    http://www.ri.cmu.edu/person.html?type=publications&person_id=696
#  - Mehmet Dogar  \\
#    student of Siddhartha co-directed by Chris \\
#    http://www.ri.cmu.edu/person.html?person_id=2068
#  - Matthew T. \\
#    Mason Director, Robotics Institute\\
#    #+ Ross' supervisor\\
#    http://www.cs.cmu.edu/~mason/
#  - Katia Sycara once talk to me
#    http://www.cs.cmu.edu/~sycara/
#  - William L. "Red" Whittaker Field Robotics Center, Robotics Institute.
#    http://www.frc.ri.cmu.edu/users/red/

